// BookBank Library service worker — generated by build-library.py.
var VERSION = 'bookbank-753cf7b403';
// Persistent cache holding user-requested full-book downloads (the shelf's
// "⤓ Offline" button fills it). Never dropped on version bumps.
var OFFLINE = 'bookbank-offline';
var SHELL = ['./', 'assets/library.css?v=9621580cc4', 'assets/library.js?v=9621580cc4',
             'catalog.json', 'manifest.webmanifest',
             'assets/icon-192.png', 'assets/icon-512.png'];

self.addEventListener('install', function (e) {
  e.waitUntil(caches.open(VERSION).then(function (c) { return c.addAll(SHELL); })
    .then(function () { return self.skipWaiting(); }));
});

self.addEventListener('activate', function (e) {
  e.waitUntil(caches.keys().then(function (keys) {
    return Promise.all(keys
      .filter(function (k) { return k !== VERSION && k !== OFFLINE; })
      .map(function (k) { return caches.delete(k); }));
  }).then(function () { return self.clients.claim(); }));
});

self.addEventListener('fetch', function (e) {
  var req = e.request;
  if (req.method !== 'GET') return;
  var url = new URL(req.url);
  if (url.origin !== location.origin) return;

  var put = function (res) {
    if (res && res.ok) {
      var copy = res.clone();
      caches.open(VERSION).then(function (c) { c.put(req, copy); });
    }
    return res;
  };

  if (req.mode === 'navigate' || url.pathname.slice(-13) === '/catalog.json') {
    e.respondWith(fetch(req).then(put).catch(function () {
      return caches.match(req).then(function (hit) {
        return hit || caches.match('./');
      });
    }));
  } else {
    e.respondWith(caches.match(req).then(function (hit) {
      var refresh = fetch(req).then(put).catch(function () { return hit; });
      return hit || refresh;
    }));
  }
});
